### ISSUE TITLE
树表和可选择同时开启时，显示错误

### ISSUE THREAD

**Issue by xxqqyy** [kingdee/kdesign#540]
## 重现问题步骤

![image](https://github.com/kdcloudone/kdesign/assets/18710890/9bb6a5d1-d0a4-43b0-b738-6ff7e79874b0)

**Comment by wqhui** [comment]
> ```js
> import React from 'react'
> import ReactDOM from 'react-dom'
> import { Table } from '@kdcloudjs/kdesign'
> 
> function Demo() {
>   const [ selected, setSelected ] = React.useState(['2'])
>   const [ selectedType, setSelectedType ] = React.useState('checkbox')
>   function renderOptions () {
>     return (
>       <div style={{display: 'flex'}}>
>         <div style={{marginRight: '5px', cursor: 'pointer', color: '#5582F3'}}>编辑</div>
>         <div style={{cursor: 'pointer', color: '#fb2323'}}>删除</div>
>       </div>
>     )
>   }
>   function makeChildren (prefix) {
>     return [
>       {
>         id: `${prefix}-1`,
>         title: '二级标题',
>         dept: '应用部',
>         dest: '云南大理',
>         guide: 'Douglas Lee',
>         children: [
>           { id: `${prefix}-1-1`, title: '三级标题', dept: '平台大前端-UED', dest: '云南大理', guide: 'Douglas Lee' },
>           { id: `${prefix}-1-2`, title: '三级标题', dept: '平台大前端-前端', dest: '云南大理', guide: 'Douglas Lee' },
>         ],
>       },
>       {
>         id: `${prefix}-2`,
>         title: '二级标题',
>         dept: '应用部',
>         dest: '云南大理',
>         guide: 'Douglas Lee',
>         children: [
>           { id: `${prefix}-2-1`, title: '三级标题', dept: '平台大前端-UED', dest: '云南大理', guide: 'Douglas Lee' },
>           { id: `${prefix}-2-2`, title: '三级标题', dept: '平台大前端-前端', dest: '云南大理', guide: 'Douglas Lee' },
>         ],
>       },
>       { id: `${prefix}-3`, title: '二级标题', dept: '应用部', dest: '云南大理', guide: 'Douglas Lee' },
>     ]
>   }
>   const dataSource = [
>     {
>       id: '1',
>       title: '一级标题',
>       dept: '云苍穹-前端',
>       dest: 'South Maddison',
>       guide: 'Don Moreno',
>       children: makeChildren('1'),
>     },
>     {
>       id: '2',
>       title: '一级标题',
>       dept: '云苍穹-模型',
>       dest: 'Emilhaven',
>       guide: 'Douglas Richards',
>       children: makeChildren('2'),
>     },
>     {
>       id: '3',
>       title: '一级标题',
>       dept: '云苍穹-基础',
>       dest: '云南大理',
>       guide: 'Douglas Lee',
>       children: makeChildren('3'),
>     },
>     {
>       id: '4',
>       title: '一级标题',
>       dept: '云苍穹-体验',
>       dest: '杭州千岛湖',
>       guide: 'Eric Castillo',
>       children: makeChildren('4'),
>     },
>     { id: '5', title: '一级标题', dept: '云苍穹-运营', dest: 'East Karl', guide: 'Herbert Patton' }
>   ]
>   const columns = [
>     { code: 'title', name: '标题', width: 200 },
>     { code: 'dept', name: '部门名称', width: 180 },
>     { code: 'dest', name: '团建目的地', width: 160 },
>     { code: 'guide', name: '当地导游', width: 160 },
>     { lock: true, name: '操作', render: renderOptions, width: 200 }
>   ]
>   const [openKeys, onChangeOpenKeys] = React.useState(['4', '4-2'])
>   const rowSelection = {
>      type: 'checkbox',
>      value:['2'],
>      onChange: setSelected,
>      column: { lock: true },
>      highlightRowWhenSelected: true
>   }
>   const treeMode = {
>       openKeys, 
>       onChangeOpenKeys
>   }
>   return (
>     <div>
>       <Table dataSource={dataSource} columns={columns} primaryKey={'id'} treeMode={treeMode}  rowSelection={rowSelection}/>
>     </div>
>   )
> }
> 
> ReactDOM.render(<Demo />, mountNode)
> ```
> 
> 代码示例如上所示

```js
  const rowSelection = {
     type: 'checkbox',
     value:['2'],//这里写死了，锁定setSelected改了没效果
     onChange: setSelected,
     column: { lock: true },
     highlightRowWhenSelected: true
  }
```

**Comment by wqhui** [comment]
> ## 重现问题步骤
> ![image](https://user-images.githubusercontent.com/18710890/262890212-9bb6a5d1-d0a4-43b0-b738-6ff7e79874b0.png)
> 
这是因为选择列的宽度问题导致，可以通过设置`treeMode.expandColCode`展开列规避该问题：
```js
  const treeMode = {
      openKeys, 
      onChangeOpenKeys,
      expandColCode: 'title'
  }
```
展示效果：
<img width="1011" alt="image" src="https://github.com/kingdee/kdesign/assets/16059309/90854e7f-2361-4ab8-9e82-4f994e37f1f2">
