### ISSUE TITLE
[Clipboard] 新组件开发

### ISSUE THREAD

**Issue by albyben** [kingdee/kdesign#584]
# 用法示例
## 1. 基础用法
```jsx
<Clipboard action="copy" content="我是要复制到剪切板的内容"/>
```
## 2. 剪切操作
```jsx
<Clipboard action="cut" content="我是要复制到剪切板的内容"/>
```
## 3. 目标内容复制
```jsx
<Clipboard action="copy"  target="#app"/>
```
## 4. 自定义复制图标
```jsx
<Clipboard action="copy" content="我是要复制到剪切板的内容" icon={<Icon type="copy">}/>
```
# API
|  属性	  | 说明        | 
|      ---      |       ---     | 
|  action	  | 操作类型，分为剪切cut和复制copy        | 
|  content  | 复制到剪切板的内容        | 
|      icon    | 自定义复制操作的图标，默认图标 copy-code       | 
|  onError   |    复制失败后的回调函数     | 
|  onSuccess  |  复制成功后的回调函数       |

**Comment by IrvingOS** [comment]
这个看似简单，实际也很简单，那就让我这个菜鸟来逝一逝吧🐶
