### ISSUE TITLE
<Table >组件缺少可以根据表头字体长度自动计算宽度的功能

### ISSUE THREAD

**Issue by NGyc** [kingdee/kdesign#653]
## 重现链接或代码
```js
![image](https://github.com/kingdee/kdesign/assets/23099333/c45b112d-be91-4203-930c-e07520e53492)
```

## 重现问题步骤
没什么属性可以自动根据字体长度计算宽度的

## 期望的结果是什么
希望能有个属性可以自动根据字体长度计算宽度

## 实际的结果是什么
当前没有这个功能

## 组件库版本号、浏览器信息
组件库与浏览器均为最新版本

**Comment by wqhui** [comment]
目前仅支持通过`column.features.flex` 让列跟flex布局一样，将网格中的剩余空间分配给所有设置了 `flex` 的列，自适应目前还在预研
