### ISSUE TITLE
<table> 启用行多选功能情况下，勾选与反勾选只能点击复选框进行操作，不能通过组件外部事件进行对表格行的勾选与反勾选

### ISSUE THREAD

**Issue by F8-Tortoise** [kingdee/kdesign#655]
## 重现问题步骤
配置了行选择配置项中的value属性值，修改value属性值，表格不会勾选或者反勾选，

## 期望的结果是什么
修改value属性值，表格会勾选或者反勾选，比如向value属性添加了a，则表格中a这一行选中，若删除，则取消选中

## 实际的结果是什么
修改value属性值，表格不会勾选或者反勾选

## 组件库版本号、浏览器信息
组件库 v1.7.14与Google Chrome版本 111.0.5563.111（正式版本） （64 位）

**Comment by F8-Tortoise** [comment]
![Uploading Image_20231124144727.png…]()

**Comment by kobehhh** [comment]
```js
import React from 'react'
import ReactDOM from 'react-dom'
import { Radio,Table } from '@kdcloudjs/kdesign'

function TableRowSelect() {
  const [selected, setSelected] = React.useState(["1", "2", "3", "5"]);
  const [selectedType, setSelectedType] = React.useState("checkbox");

  const handleSelectedTypeChange = (e) => {
    setSelected(selected.splice(0, 1));
    setSelectedType(e.target.value);
  };

  const dataSource = [
    {
      id: "1",
      No: 1,
      order: "AP-202009-00001",
      from: "陕西环宇科技",
      to: "深圳环球科技",
      amount: "26,800.00",
      balance: "5,200.00",
    },
    {
      id: "2",
      No: 2,
      order: "AP-202009-00001",
      from: "陕西环宇科技",
      to: "深圳环球科技",
      amount: "236,800.00",
      balance: "1,500.00",
    },
    {
      id: "3",
      No: 3,
      order: "AP-202009-00002",
      from: "陕西环宇科技",
      to: "深圳环球科技",
      amount: "246,800.00",
      balance: "5,300.00",
    },
    {
      id: "4",
      No: 4,
      order: "AP-202009-00003",
      from: "陕西环宇科技",
      to: "深圳环球科技",
      amount: "216,800.00",
      balance: "5,400.00",
    },
    {
      id: "5",
      No: 5,
      order: "AP-202009-00004",
      from: "陕西环宇科技",
      to: "深圳环球科技",
      amount: "236,800.00",
      balance: "1,500.00",
    },
  ];

  const columns = [
    { code: "No", name: "序号", width: 60, align: "center" },
    { code: "order", name: "单据号", width: 200 },
    { code: "from", name: "来户", width: 200 },
    { code: "to", name: "往户", width: 200 },
    { code: "amount", name: "应付金额", width: 150, align: "right" },
    { code: "balance", name: "应收余额", width: 150, align: "right" },
  ];

  const rowSelection = {
    type: selectedType,
    value: selected,
    onChange: setSelected,
    column: { lock: true },
    highlightRowWhenSelected: true,
  };

  return (
    <div style={{ width: 875 }}>
      <Radio.Group onChange={handleSelectedTypeChange} value={selectedType}>
        <Radio value={"checkbox"}>多选</Radio>
        <Radio value={"radio"}>单选</Radio>
      </Radio.Group>
      <br />
      <Table
        columns={columns}
        dataSource={dataSource}
        rowSelection={rowSelection}
        primaryKey={"id"}
      />
      {selected.map((item) => {
        return (
          <div
            style={{ height: 30, background: "#eee", marginBottom: 10 }}
            key={item}
            onClick={() => {
              const index = selected.indexOf(item);
              if (index > -1) {
                selected.splice(index, 1);
              } else {
                selected.push(item);
              }
              setSelected(selected);
              console.log("selected", selected);
            }}
          >
            {item}
          </div>
        );
      })}
    </div>
  );
}
ReactDOM.render(<TableRowSelect />, mountNode)
```
外部更改selected后不会同步改动table的选中项

**Comment by wqhui** [comment]
> ```js
> import React from 'react'
> import ReactDOM from 'react-dom'
> import { Radio,Table } from '@kdcloudjs/kdesign'
> 
> function TableRowSelect() {
>   const [selected, setSelected] = React.useState(["1", "2", "3", "5"]);
>   const [selectedType, setSelectedType] = React.useState("checkbox");
> 
>   const handleSelectedTypeChange = (e) => {
>     setSelected(selected.splice(0, 1));
>     setSelectedType(e.target.value);
>   };
> 
>   const dataSource = [
>     {
>       id: "1",
>       No: 1,
>       order: "AP-202009-00001",
>       from: "陕西环宇科技",
>       to: "深圳环球科技",
>       amount: "26,800.00",
>       balance: "5,200.00",
>     },
>     {
>       id: "2",
>       No: 2,
>       order: "AP-202009-00001",
>       from: "陕西环宇科技",
>       to: "深圳环球科技",
>       amount: "236,800.00",
>       balance: "1,500.00",
>     },
>     {
>       id: "3",
>       No: 3,
>       order: "AP-202009-00002",
>       from: "陕西环宇科技",
>       to: "深圳环球科技",
>       amount: "246,800.00",
>       balance: "5,300.00",
>     },
>     {
>       id: "4",
>       No: 4,
>       order: "AP-202009-00003",
>       from: "陕西环宇科技",
>       to: "深圳环球科技",
>       amount: "216,800.00",
>       balance: "5,400.00",
>     },
>     {
>       id: "5",
>       No: 5,
>       order: "AP-202009-00004",
>       from: "陕西环宇科技",
>       to: "深圳环球科技",
>       amount: "236,800.00",
>       balance: "1,500.00",
>     },
>   ];
> 
>   const columns = [
>     { code: "No", name: "序号", width: 60, align: "center" },
>     { code: "order", name: "单据号", width: 200 },
>     { code: "from", name: "来户", width: 200 },
>     { code: "to", name: "往户", width: 200 },
>     { code: "amount", name: "应付金额", width: 150, align: "right" },
>     { code: "balance", name: "应收余额", width: 150, align: "right" },
>   ];
> 
>   const rowSelection = {
>     type: selectedType,
>     value: selected,
>     onChange: setSelected,
>     column: { lock: true },
>     highlightRowWhenSelected: true,
>   };
> 
>   return (
>     <div style={{ width: 875 }}>
>       <Radio.Group onChange={handleSelectedTypeChange} value={selectedType}>
>         <Radio value={"checkbox"}>多选</Radio>
>         <Radio value={"radio"}>单选</Radio>
>       </Radio.Group>
>       <br />
>       <Table
>         columns={columns}
>         dataSource={dataSource}
>         rowSelection={rowSelection}
>         primaryKey={"id"}
>       />
>       {selected.map((item) => {
>         return (
>           <div
>             style={{ height: 30, background: "#eee", marginBottom: 10 }}
>             key={item}
>             onClick={() => {
>               const index = selected.indexOf(item);
>               if (index > -1) {
>                 selected.splice(index, 1);
>               } else {
>                 selected.push(item);
>               }
>               setSelected(selected);
>               console.log("selected", selected);
>             }}
>           >
>             {item}
>           </div>
>         );
>       })}
>     </div>
>   );
> }
> ReactDOM.render(<TableRowSelect />, mountNode)
> ```
> 
> 点击表格下方的div更改selected后不会同步到table的选中项

看了一下，底部的代码直接修改了`selected`导致异常了，如果是原生的可变对象，尽量避免操作`state`的对象，对原数据操作前生成一个新数组即可：`const resetSelect = [...selected]`
```js
      {selected.map((item) => {
        return (
          <div
            style={{ height: 30, background: "#eee", marginBottom: 10 }}
            key={item}
            onClick={() => {
              const resetSelect = [...selected]
              const index = resetSelect.indexOf(item);
              if (index > -1) {
                resetSelect.splice(index, 1);
              } else {
                resetSelect.push(item);
              }
              setSelected(resetSelect);
              console.log("selected", resetSelect);
            }}
          >
            {item}
          </div>
        );
      })}
```
