### ISSUE TITLE
【Table】在 Vite5 下无法渲染

### ISSUE THREAD

**Issue by makeng** [kingdee/kdesign#711]
## 重现链接或代码
```js
  const dataSource = [
    {
      id: '1',
      order: 'AP-202009-00001',
    },
    {
      id: '2',
      order: 'AP-202009-00001',
    },
  ];
  const columns = [
    { code: 'id', name: 'id' },
    { code: 'order', name: '单据号' },
  ];

  return <Table dataSource={dataSource} columns={columns} />;
```

## 重现问题步骤
用 Vite React App 启动

## 期望的结果是什么
正常渲染

## 实际的结果是什么
白屏报错
![WX20240110-144950](https://github.com/kingdee/kdesign/assets/23654388/4883decd-d215-41c0-b86e-649e97ded143)

## 组件库版本号、浏览器信息
组件库与浏览器均为最新版本。感觉是 React 18.2.0 的兼容问题。

**Comment by albyben** [comment]
在版本v1.7.45版本已处理完，看这里 https://github.com/kingdee/kdesign/issues/695
