### ISSUE TITLE
[ColorPicker] 希望组件能识别value类型，自动把类型赋给选项

### ISSUE THREAD

**Issue by xiaoman-Xie** [kingdee/kdesign#841]
## 重现问题步骤
![image](https://github.com/user-attachments/assets/63fa0b64-3aea-4f79-a1e2-c841bad97fd5)
![image](https://github.com/user-attachments/assets/5bbf31db-2a0d-45c0-bdca-eb4d0a1c7124)

## 组件库版本号、浏览器信息
组件库与浏览器均为最新版本

**Comment by albyben** [comment]
1. 输入框输入的格式不会影响下面的格式选择，交互没办法修改，目前在准备新版本的更新迭代，会增加格式的明显区分
2. 转化为其他前端不支持的格式，可以利用change传出的第二个参数，转化输出为前端支持的颜色格式
