### ISSUE TITLE
多选下拉tag交互优化建议

### ISSUE THREAD

**Issue by xxqqyy** [kingdee/kdesign#853]
![image](https://github.com/user-attachments/assets/6dcabf2e-69f5-486f-a7cc-844799f9c02d)
多选下来现在只能设置maxTagCount来展示，但是因为选项的文本长度不是固定的，如果给maxTagCount设置一个固定值，就会出来下拉框换行的情况，建议根据框的长度自动计算能展示多少个tag

## 组件库版本号、浏览器信息
组件库与浏览器均为最新版本

**Comment by albyben** [comment]
这其中有很多不确定性，其中有两种场景需要考虑:
1. 用户选择的选项本身就很长，已经超出目前输入框的宽度，应该如何去显示，如果不换行的话
2. 用户选择几项后，比如有 `aaaaaaa` `bbbbbbb` `ccccccc` 后选择`ddddddd`，此时加上`ddddddd`肯定超出一行了，需要加上`共x行`，加上后也将超出一行，此时需要去除`ccccccc`,显示`共x行`，可能会让用户误解。
可能还要很多原因。后续有好的方案可以考虑
